app/organisation/forms.py
from flask_login import current_user
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import InputRequired, Length, ValidationError

from app.models import Organisation


class OrganisationForm(FlaskForm):
    name = StringField(
        "Name",
        validators=[
            InputRequired(message="Enter a name"),
        ],
        description="The name of the organisation, company, business or institution",
    )

    domain = StringField(
        "Domain name",
        validators=[
            InputRequired(message="Enter a domain name"),
            Length(max=255, message="Domain name must be 255 characters or fewer"),
        ],
    )

    def validate_domain(self, domain):
        # If organisation has changed domains, prevent duplication with another organisation
        if current_user.organisation and current_user.organisation.domain != domain.data:
           raise ValidationError("Domain name is already in use")


class OrganisationDeleteForm(FlaskForm):
    pass

app/organisation/__init__.py
from flask import Blueprint

bp = Blueprint(
    "organisation",
    __name__,
    template_folder="../templates/organisation",
    url_prefix="/organisation",
)

from app.organisation import routes  # noqa: E402,F401

app/organisation/routes.py
from datetime import datetime

import pytz
from flask import flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from werkzeug.exceptions import Forbidden

from app import db, limiter
from app.models import Organisation
from app.organisation import bp
from app.organisation.forms import OrganisationDeleteForm, OrganisationForm


@bp.route("/new", methods=["GET", "POST"])
@login_required
@limiter.limit("2 per second", key_func=lambda: current_user.id)
def create():
    """Create a new Organisation."""

    # Prevent authenticated users from creating a new organisation if they're already in one
    if current_user.organisation_id:
        raise Forbidden()

    form = OrganisationForm()

    if form.validate_on_submit():
        new_organisation = Organisation(name=form.name.data.strip(), domain=form.domain.data.strip())
        current_user.organisation_id = new_organisation.id
        current_user.role = "admin"
        db.session.add(new_organisation)
        db.session.add(current_user)
        db.session.commit()
        flash(
            f"<a href='{url_for('organisation.view')}' class='alert-link'>{new_organisation.name}</a> has been created.",
            "success",
        )
        return redirect(url_for("main.index"))

    return render_template("create_organisation.html", title="Create a new organisation", form=form)


@bp.route("/", methods=["GET"])
@login_required
@limiter.limit("2 per second", key_func=lambda: current_user.id)
def view():
    """View the authenticated users organisation."""
    return render_template("view_organisation.html", title=current_user.organisation.name)


@bp.route("/edit", methods=["GET", "POST"])
@login_required
@limiter.limit("2 per second", key_func=lambda: current_user.id)
def edit():
    """Edit the authenticated users organisation."""

    # Only allow admins to edit their own organisation
    if current_user.role != "admin":
        raise Forbidden()

    form = OrganisationForm()

    if form.validate_on_submit():
        current_user.organisation.name = form.name.data.strip()
        current_user.organisation.domain = form.domain.data.lower().strip()
        current_user.organisation.updated_at = pytz.utc.localize(datetime.utcnow())
        db.session.add(current_user)
        db.session.commit()
        flash(
            f"Your changes to <a href='{url_for('organisation.view')}' class='alert-link'>{current_user.organisation.name}</a> have been saved.",
            "success",
        )
        return redirect(url_for("main.index"))
    elif request.method == "GET":
        form.name.data = current_user.organisation.name
        form.domain.data = current_user.organisation.domain

    return render_template(
        "update_organisation.html",
        title="Edit organisation",
        form=form,
    )


@bp.route("/delete", methods=["GET", "POST"])
@login_required
@limiter.limit("2 per second", key_func=lambda: current_user.id)
def delete():
    """Delete the authenticated users organisation."""

    # Only allow admins to delete their own organisation
    if current_user.role != "admin":
        raise Forbidden()

    form = OrganisationDeleteForm()

    if request.method == "GET":
        return render_template(
            "delete_organisation.html",
            title="Delete organisation",
            form=form,
        )
    elif request.method == "POST":
        org = current_user.organisation.name
        db.session.delete(current_user.organisation)
        db.session.commit()
        flash(f"{org} has been deleted.", "success")
        return redirect(url_for("main.index"))

app/templates/organisation/_organisation_description.html
<dl class="row">
    <dt class="col-sm-3">Domain</dt>
    <dd class="col-sm-9">{{ current_user.organisation.domain }}</dd>

    <dt class="col-sm-3">Users</dt>
    <dd class="col-sm-9">{{ current_user.organisation.users | length }}</dd>

    <dt class="col-sm-3">Created</dt>
    <dd class="col-sm-9">{{ current_user.organisation.created_at.strftime("%d/%m/%Y") }} at {{ current_user.organisation.created_at.strftime("%H:%M:%S") }}</dd>

    <dt class="col-sm-3">Last updated</dt>
    <dd class="col-sm-9">
    {% if current_user.organisation.updated_at %}
        {{ current_user.organisation.updated_at.strftime("%d/%m/%Y") }} at {{ current_user.organisation.updated_at.strftime("%H:%M:%S") }}
    {% else %}
        Never
    {% endif %}
    </dd>
</dl>

app/templates/organisation/_organisation_form.html
<form action="" method="post" novalidate>
    {{ form.csrf_token }}
    <div class="mb-3">
        {{ form.name.label(class="form-label") }}
        {% if form.errors %}
            {% if form.name.errors %}
                {{ form.name(class="form-control is-invalid", type="text", spellcheck="true", autocomplete="name", aria_describedby="nameHelp") }}
                {% for error in form.name.errors %}<div class="invalid-feedback">{{error}}</div>{% endfor %}
            {% else %}
                {{ form.name(class="form-control is-valid", type="text", spellcheck="true", autocomplete="name", aria_describedby="nameHelp") }}
                <div class="valid-feedback">Looks good!</div>
            {% endif %}
        {% else %}
            {{ form.name(class="form-control", type="text", spellcheck="true", autocomplete="name", aria_describedby="nameHelp") }}
        {% endif %}
        <div id="nameHelp" class="form-text">{{ form.name.description }}</div>
    </div>
    <div class="mb-3">
        {{ form.domain.label(class="form-label") }}
        {{ form.domain(class="form-control-plaintext", readonly="readonly", type="text", spellcheck="true", aria_describedby="domainHelp", value=current_user.email_address.split('@')[1]) }}
        <div id="domainHelp" class="form-text">{{ form.domain.description }}</div>
    </div>
    <div class="d-grid gap-3 d-sm-block">
        <button class="btn btn-primary" type="submit"><i class="bi bi-save"></i> Save</button>
        <a class="btn btn-secondary" href="{{ request.referrer }}"><i class="bi bi-chevron-left"></i> Cancel</a>
    </div>
</form>

app/templates/organisation/create_organisation.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        {{ super() }}
        <h1>{{title}}</h1>
        <hr>
        {% include '_organisation_form.html' %}
    </div>
</div>
{% endblock %}

app/templates/organisation/delete_organisation.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url_for('organisation.view') }}">{{ current_user.organisation.name }}</a></li>
                <li class="breadcrumb-item active" aria-current="page">Delete</li>
            </ol>
        </nav>
        {{ super() }}
        <h1>{{title}}</h1>
        <hr>
        <p class="lead">Are you sure you want to delete {{ current_user.organisation.name }}?</p>
        {% include '_organisation_description.html' %}
        <form action="" method="post" novalidate>
            {{ form.csrf_token }}
            <div class="d-grid gap-3 d-sm-block">
                <button class="btn btn-danger" type="submit"><i class="bi bi-trash"></i> Yes, delete {{ current_user.organisation.name }} and {{ current_user.organisation.users | length }} users</button>
                <a class="btn btn-secondary" href="{{ request.referrer }}"><i class="bi bi-chevron-left"></i> Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

app/templates/organisation/update_organisation.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url_for('organisation.view') }}">{{ current_user.organisation.name }}</a></li>
                <li class="breadcrumb-item active" aria-current="page">Edit</li>
            </ol>
        </nav>
        {{ super() }}
        <h1>{{title}}</h1>
        <hr>
        {% include '_organisation_form.html' %}
    </div>
</div>
{% endblock %}

app/templates/organisation/view_organisation.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        {{ super() }}
        <h1 class="text-truncate">{{ title }}</h1>
        <hr>
        {% include '_organisation_description.html' %}
        {% if current_user.role == "admin" %}
        <div class="d-grid gap-3 d-sm-block">
            <a class="btn btn-primary" href="{{ url_for('organisation.edit') }}"><i class="bi bi-pencil-square"></i> Edit</a>
            <a class="btn btn-danger" href="{{ url_for('organisation.delete') }}"><i class="bi bi-trash"></i> Delete</a>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}